/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package selatexpack;

import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author susma
 */
public class wizard2 extends javax.swing.JFrame {
    private int clicked = 0;
    private int checked = 0;
    Clipboard clip= getToolkit().getSystemClipboard();
    private String wizard1="",t="",st="",a="",d="";
    
    private String latexcode="";
    /**
     * Creates new form doc1
     */
    public wizard2() {
        initComponents();
    }
    public wizard2(String w,String title,String subtitle,String author,String date) {
        initComponents();
        wizard1=w;
        t=title;
        st=subtitle;
        a=author;
        d=date;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        addpointer = new javax.swing.JButton();
        addpathindescription = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        code = new javax.swing.JTextArea();
        title = new javax.swing.JTextField();
        section = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pointer = new javax.swing.JTextArea();
        addcode = new javax.swing.JButton();
        end = new javax.swing.JButton();
        path = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        rightarrow = new javax.swing.JButton();
        copycode = new javax.swing.JButton();
        subsection = new javax.swing.JCheckBox();
        back = new javax.swing.JButton();
        starten = new javax.swing.JCheckBox();
        rightarrow2 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane6.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addpointer.setText("Add item");
        addpointer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpointerActionPerformed(evt);
            }
        });

        addpathindescription.setText("Add Path");
        addpathindescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpathindescriptionActionPerformed(evt);
            }
        });

        code.setColumns(20);
        code.setLineWrap(true);
        code.setRows(5);
        code.setWrapStyleWord(true);
        code.setNextFocusableComponent(path);
        jScrollPane3.setViewportView(code);

        title.setNextFocusableComponent(description);
        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                titleMouseMoved(evt);
            }
        });
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });

        section.setText("Add Section");
        section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionActionPerformed(evt);
            }
        });

        description.setLineWrap(true);
        description.setRows(5);
        description.setWrapStyleWord(true);
        description.setNextFocusableComponent(pointer);
        jScrollPane1.setViewportView(description);

        pointer.setColumns(20);
        pointer.setLineWrap(true);
        pointer.setRows(5);
        pointer.setWrapStyleWord(true);
        jScrollPane2.setViewportView(pointer);

        addcode.setText("Add code");
        addcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcodeActionPerformed(evt);
            }
        });

        end.setText("End");
        end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endActionPerformed(evt);
            }
        });

        path.setNextFocusableComponent(addpathindescription);
        path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Description:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Path:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Java code:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Item:");

        output.setLineWrap(true);
        output.setRows(5);
        output.setWrapStyleWord(true);
        output.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                outputMouseMoved(evt);
            }
        });
        output.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                outputMouseEntered(evt);
            }
        });
        output.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                outputKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(output);

        rightarrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selatexpack/left1.jpg"))); // NOI18N
        rightarrow.setText("LeftArrow");
        rightarrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightarrowActionPerformed(evt);
            }
        });

        copycode.setText("Copy code");
        copycode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copycodeActionPerformed(evt);
            }
        });

        subsection.setText("Subsection");
        subsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subsectionActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        starten.setText("Start enumerate");
        starten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startenActionPerformed(evt);
            }
        });

        rightarrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/selatexpack/arrow-symbol-material-conditional-latex-mathematics-png-favpng-QjcehHbKGzkxbCQ1BseU10Z6q.jpg"))); // NOI18N
        rightarrow2.setText("RightArrow");
        rightarrow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightarrow2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rightarrow)
                                .addGap(44, 44, 44)
                                .addComponent(rightarrow2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addpathindescription)
                                        .addComponent(addcode)
                                        .addComponent(starten)
                                        .addComponent(addpointer))
                                    .addComponent(subsection))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(section)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(back)
                                        .addGap(52, 52, 52)
                                        .addComponent(end)
                                        .addGap(61, 61, 61)
                                        .addComponent(copycode))
                                    .addComponent(title)
                                    .addComponent(jScrollPane2)
                                    .addComponent(jScrollPane3)
                                    .addComponent(path)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subsection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightarrow)
                    .addComponent(rightarrow2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(starten)
                        .addGap(65, 65, 65)
                        .addComponent(addpointer))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addcode)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addpathindescription)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copycode)
                    .addComponent(end)
                    .addComponent(back)
                    .addComponent(section))
                .addGap(0, 0, 0))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleActionPerformed

    private void addcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcodeActionPerformed
        // TODO add your handling code here:
        if(starten.isSelected()){
        pointer.setText(pointer.getText()+"\n"+"\\begin{lstlisting}[language=Java]%, caption=HelloWorld example]"+"\n"+code.getText()+"\n"+"\\end{lstlisting}");
        /*desc1.setText(desc1.getText()+"\n"+ac);
        ac="";
        d+="\n"+desc1.getText()+"\n"+"\\begin{lstlisting}[language=Java]%, caption=HelloWorld example]"+"\n"+code.getText()+"\n"+"\\end{lstlisting}";
        code.setText("");*/
        }
        else{
            description.setText(description.getText()+"\n"+"\\begin{lstlisting}[language=Java]%, caption=HelloWorld example]"+"\n"+code.getText()+"\n"+"\\end{lstlisting}");
        }
        code.setText("");
        
    }//GEN-LAST:event_addcodeActionPerformed

    private void addpointerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpointerActionPerformed
        // TODO add your handling code here:
        /*
        if((poin.getText()).equals(".      ")) api+="\\item"+poin.getText()+"\n";
        api="\\begin{enumerate}"+"\n"+"\\item"+poin.getText();
        */
       if(starten.isSelected()){
        if("".equals(pointer.getText())) JOptionPane.showMessageDialog(null,"Your item is empty");
        else if(checked==0){
        description.setText(description.getText()+"\n"+"\\begin{enumerate}"+"\n"+"\\item"+" "+pointer.getText());
        pointer.setText("");
        checked++;
        }
        else{
            description.setText(description.getText()+"\n"+"\\item"+" "+pointer.getText());
            pointer.setText("");
        checked++;
        }
    }
       else{
           JOptionPane.showMessageDialog(null,"Please click on start enumerate checkbox");
       }
    }//GEN-LAST:event_addpointerActionPerformed

    private void sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionActionPerformed
        // TODO add your handling code here:
        /*
        tex[i]="";
        i++;
        */
        
        if(subsection.isSelected()){
            if(clicked==0){
            JOptionPane.showMessageDialog(null,"Add Section First!!!");
        }
            else if("".equals(title.getText())){
            JOptionPane.showMessageDialog(null,"Please add subsection name!");
        }
            else if("".equals(description.getText())){
            JOptionPane.showMessageDialog(null,"Please add description!");
        }
        else{
        latexcode+="\n"+"\\subsection{"+title.getText()+"}"+"\n"+ description.getText();
        title.setText("");
        description.setText("");
        }
        }
        else{
            if("".equals(title.getText())){
            JOptionPane.showMessageDialog(null,"Please add section name!");
        }else{
        latexcode+="\n"+"\\section{"+title.getText()+"}"+"\n"+ description.getText();
        title.setText("");
        description.setText("");
            }
        }
        clicked++;
        /*
        tex[i]="\\section{"+title.getText()+"}"+"\n"+desc1.getText()+"\n"+"\\end{document}";
        i++
        for (String tex1 : tex) {
            d=d +"\n"+tex1;        }
        System.out.println(d);
        */
    }//GEN-LAST:event_sectionActionPerformed

    private void addpathindescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpathindescriptionActionPerformed
        // TODO add your handling code here:
        /*
        d+="\n"+desc1.getText()+"\n"+"\\path{"+pd.getText()+"}";
        */
        if(starten.isSelected()) pointer.setText(pointer.getText()+" "+"\\path{"+path.getText()+"}");
        else {description.setText(description.getText()+" "+"\\path{"+path.getText()+"}");}
        path.setText("");
    }//GEN-LAST:event_addpathindescriptionActionPerformed

    private void pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathActionPerformed

    private void titleMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_titleMouseMoved

    private void endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endActionPerformed
        // TODO add your handling code here:
        output.setText(output.getText()+"\n"+"\\end{document}");
        try{
        FileWriter Writer=new FileWriter("latex.tex", true);
        Writer.write("");
        Writer.write(output.getText());
        Writer.write(System.getProperty("line.separator"));
        Writer.close();
        JOptionPane.showMessageDialog(null,"Tex file created successfully");
        this.setVisible(false);
    }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_endActionPerformed

    private void rightarrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightarrowActionPerformed
        // TODO add your handling code here:
        if(starten.isSelected()) pointer.setText(pointer.getText()+" "+"$\\Leftarrow$");
        else {description.setText(description.getText()+" "+"$\\Leftarrow$");}
    }//GEN-LAST:event_rightarrowActionPerformed

    private void copycodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copycodeActionPerformed
        // TODO add your handling code here:
        String toclipboard= output.getText();
        StringSelection stringclip = new StringSelection(toclipboard);
        clip.setContents(stringclip, stringclip);
    }//GEN-LAST:event_copycodeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        wizard sendingdatatowizard = new wizard(latexcode,t,st,a,d); 
        sendingdatatowizard.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void subsectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subsectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subsectionActionPerformed

    private void outputMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputMouseMoved
        // TODO add your handling code here:
        
    }//GEN-LAST:event_outputMouseMoved

    private void startenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startenActionPerformed
        // TODO add your handling code here:
        if(!starten.isSelected()) {
            if(checked==0){}
        else{
            description.setText(description.getText()+"\n"+"\\end{enumerate}");
                }
        }
        checked=0;
    }//GEN-LAST:event_startenActionPerformed

    private void outputMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outputMouseEntered
        // TODO add your handling code here:
        
        output.setText(wizard1+"\n"+latexcode);
    }//GEN-LAST:event_outputMouseEntered

    private void outputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outputKeyTyped
        // TODO add your handling code here:
        latexcode=output.getText().split("\\date{"+d+"}",2)[1];
        //latexcode+="\\begin{document}\n" + "\\maketitle"+"\n"+ latexcode;
        output.setText(wizard1+"\n"+ latexcode);
    }//GEN-LAST:event_outputKeyTyped

    private void rightarrow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightarrow2ActionPerformed
        // TODO add your handling code here:
        if(starten.isSelected()) pointer.setText(pointer.getText()+" "+"$\\Rightarrow$");
        else {description.setText(description.getText()+" "+"$\\Rightarrow$");}
    }//GEN-LAST:event_rightarrow2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wizard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wizard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wizard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wizard2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wizard2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcode;
    private javax.swing.JButton addpathindescription;
    private javax.swing.JButton addpointer;
    private javax.swing.JButton back;
    private javax.swing.JTextArea code;
    private javax.swing.JButton copycode;
    private javax.swing.JTextArea description;
    private javax.swing.JButton end;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea output;
    private javax.swing.JTextField path;
    private javax.swing.JTextArea pointer;
    private javax.swing.JButton rightarrow;
    private javax.swing.JButton rightarrow2;
    private javax.swing.JButton section;
    private javax.swing.JCheckBox starten;
    private javax.swing.JCheckBox subsection;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
}
